# Generated by Django 2.0.7 on 2018-08-07 18:14

import blogs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('content', models.TextField(max_length=140)),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=models.SET(blogs.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
